{'author': 'Advitus',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['security/ir.model.access.csv',
          'views/assets.xml',
          'views/snippet.xml',
          'views/website_snippet.xml',
          'views/templates.xml'],
 'demo': [],
 'depends': ['website'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/website_snippet/14.0',
 'name': 'Create Custom Building Blocks',
 'price': 50.0,
 'qweb': ['static/src/xml/*.xml'],
 'summary': 'Create your own custom Building Blocks',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '14.0.1.0.0',
 'website': 'https://demo.minilini.com'}

